# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ars.me.cba
tagline:             'Administradores de Red . Ministerio de Educación .  Córdoba'
description:         'Made by <a href="https://github.com/gchamorro" target="_blank">G.Chamorro</a>.'
url:                 http://gchamorro.github.io
baseurl:             '/ars-me-cba'

# About/contact
#author:
# name:              Mark Otto
#  url:               https://twitter.com/mdo
#  email:             markdotto@gmail.com

# Custom vars
#version:             1.0.0


collections:
  instructivos:
    output: true
    permalink: /instructivos/:path/
    
gems:
  - jekyll-redirect-from
